
language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - secure: Dcw2b00aVho7kJwPVlbN/4BmTLNRaHHvSXr38mQ3VjKuEx5stkpFCJLnyW3UpgFxCrcs0DybvptUMrMuhpr2OxTAk5htyyIGywPSIOWQ8/pgVgZExUtoFMFhJ+9xZtVnDnRkAxS+4r7toFoOilEQoysRQg205HPEvpi4NarLJMz3BgF23E/wRLCSKyQCz1qK53n1oU//cog7dBSXe6sf0LraOsjXgReo++4xquRe6lVcLh2BWlToBJxKCMeuzZ9a4p2AwuKsThA1jg22JITIwo/gaGLc45vRkazgj4lIdHchqgRI65rgzPOyAJLRrK93T0TRdu1VLZSJbMpivNQX3Vl4ncIjYaEv6YeWftY089NrqlsyKD7jmmNpmFsnc3UebSvZ5JjvCi35r3UwalhhNInBHIrxFjtZaxBnsf3qUvvcOY1hK+zQMG2UrPwcgLNcihPC+s5yDJFwSxCcQdyLJS+uRQvGGqSG+uky66J+aR/jCYgGyS8vu7l3WuSiD1tJr7uUO9VwbJ02nFCIA6DmlUt0jEpU6Rs7NT12QrQAr/gk+FiKbtA2JejdV0vFC7x2VUMyoAcUQYby5DtmGQNSeXoW9nChgDmNdqRU7wtkJy0v81YSmZ4hbzEbVbRKfbrH1kMGMjC2/uIBPPtfnC4mEk88qi6LvFxycCkYfxloUFQ=


before_install:
- nvm install 8.11.1
- npm install -g ionic cordova
- echo "Before Install Step"

install:
- echo "Install Step"
- npm install -g ionic cordova

before_script:
- echo "Before Script Step"

script:
- echo "Script Step"
- npm i
- rm -rf platforms
- ionic cordova platform add android
- ionic cordova build android

before_cache:
- echo "Before cache Step"

cache:
- echo "Cache Step"

after_success:
- echo "After Success Step"

after_failure:
- echo "After failure Step"

before_deploy:
- echo "Before Deploy Step."
deploy:
  provider: releases
  api_key:
    secure: su8f8rR0NU8ueenSFlxfCJUfoAThVpUiQljZOWK/PUbo3e+pnqh6bMoZwp0azxx+8vM5MyYzstJ/qOg+aUz78MxUmnoBcEbAlCwNdy/tCMrI69RlkJgJ3ErkJDdgp7rmz5Qr0gGvL6YwbQMvLO07stt0JnfS9SZ0uKDPcFKG0Vh8ZoOnBDygSl1o3dWRaT6wuYENMO7pVG+VTw1mqjZsrvC+V9XXX56jWHPfTj3bZI6cJHjI6ZAScISUyw8Gu0WdU7ez/jOamvhJSYU6DOCBuCp7UgBKUJbokBBSDZnZrIW1jGewR6mjjH/2fS3OyEDULIvdI7e+/+7OU5ZM6wMFNybFBZR2UPaEC3iGVb3V6X+321GzriqBTlobX/ZZonerbzmjK6S6jO10uMG0jWOjSA5PDZhgJC3IO+GhphTh2fok8geG9kl6waOGpG6YuRIcywlsUwPMnsf9usGnUovCUvRUXNhM8VUAMiam6SlP2HHQ7SJnqUDWmuHjaAzlwcK/kDur0JqAcP9omL/aojsQIyx4cNJIgWTODafx/xWtSt/hF9A56EiAW6Uszvsexd7eQaTNWHn7s0OaWqyUS1PzvRHVDjlAA0arqBLgE45IF9mXA6YwEypv0XZnNt3V6Ck7dbaF+5RlLquDgc34RQFMt5rHnC72UmSNj8PNZ9ay7kM=
  file_glob: true
  file: platforms/android/app/build/outputs/apk/debug/app-debug.apk
  overwrite: true
  skip_cleanup: true
  on:
    repo: Ionic-SpaceX/SpaceX
    tags: true
    all_branches: true
  provider: heroku
    api_key:
      secure: W8L9weyA+a6gXQM1BZ0ihn3sprkUuFyokys0cTu0T0UdffYbQqLc7W/9wgGNWcQJlplGND/b2PSkMbg6rJpGM/2q+faoDTCbAhwDHlITKetyiF+f03KIB6UsWd67NiYQnOxPbGZ8XkQ3Dy1A+LLcgoN11C4/pCawhCvyLWyKCvc2qYYfF9yxaJT+lPmaMaXQ6BWjiJah+KeRD7Rm77xcKBW1k2OLJ1UduNPPRKeezJ0ATfyx/XZBoMKSKDfW3plnUd4FD/Wmq0mgzn1bJrA+K2wO5kCJiSC8NwHs5QalNruBlnQxDTh34cx9VppS++YzN0ekwDHhC2aOcenfQgtEDoaf/Ouz4kYe3VoSVhLfxyUX3RyRV7DdUZ7b24R9YGPgRoEahTkBkb6+qpXcujYAYna4JRDfLoX/ihcVnpWTsA9uHlHCRGlF/8Ew1Uk3pppBaCBBfweqyhIg/bbcCeSaYMIUYjTVXAGR/IUWQPVFG35fNeH1t1wg+G/n30x9K2eszycGNxsap90P5nM0QNM0jQZH9Hi++fiIb01MWGFUQ789e2yrKqnzg86EOm7blZ2p3MzSklz5yOfLdWoOT0awLv3BotR0YEENKxy5Mfo+2y3u4xrbf/5Ztvq1wR38LYcMe/E+uh0ywmRZx932b3jH2d9+pFIJXREavmJD6mU0Y7w=
    app: spacex-esgi
    on:
      repo: Ionic-SpaceX/SpaceX
